{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rails.fullname" . }}
data:
{{- range $key, $value := .Values.configMap.keys }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}